How to pre-commit in Docker Development
pydanny/cookiecutter-django pull request #3287
Opened 2021-08-06 14:57 UTC by Qoyyuum

## Description

It is clear that pre-commit cannot work inside Docker containers and it can only work with git stored on the local machine since its not in a shared volume with the containers. Therefore, it should be noted that anyone who uses this cookicutter with pre-commit already generated by default in every project, should start using pre-commit into their general workflow.

Checklist:

- [ ] I've made sure that `tests/test_cookiecutter_generation.py` is updated accordingly (especially if adding or updating a template option)
- [ * ] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

Fixes #3086

2021-08-06 21:32 UTC, Andrew-Chen-Wang requested changes
You shouldn't install everything from local.txt. Simply doing pre-commit install is good enough as an environment with all the needed hooks are stored elsewhere, not inside a virtual environment. Instead, the docs should say "to use pre-commit, you should have pre-commit installed globally"

2021-08-07 15:44 UTC, Qoyyuum commented
> 
> 
> You shouldn't install everything from local.txt. Simply doing pre-commit install is good enough as an environment with all the needed hooks are stored elsewhere, not inside a virtual environment. Instead, the docs should say "to use pre-commit, you should have pre-commit installed globally"

Good idea. I've reworded it so it should be installed as part of a prerequisite.

2021-08-07 18:57 UTC, Andrew-Chen-Wang approved these changes

2021-08-12 07:00 UTC, browniebroke approved these changes

2021-08-12 07:04 UTC, merged

2021-08-12 07:05 UTC, browniebroke commented
Thanks for the clarification!